FORMAT_REPORT_TYPE = {
    "partywise_sales_summary": "Party-wise Sales",
    "customer_invoice_itemwise_sale": "Party-wise Sales",
    "sales_statement_summary_itemwise": "Party-wise Sales",
    "mfacwise_custwise_itemwise": "Party-wise Sales",
    "prodcust_wise_billwise": "Party-wise Sales",
    "areaprod_wise_billwise": "Party-wise Sales",
    "customer_product_wise_packing": "Party-wise Sales",
    "party_item_summary_qtyfree": "Party-wise Sales",
    "areawise_sales_statement_banded": "Party-wise Sales",
    "areawise_sales_statement_packing": "Party-wise Sales",
    "prompt_billwise_mixed": "Party-wise Sales",
    "shivasakthi_areawise_billwise": "Party-wise Sales",
    "vasan_areawise_billwise": "Party-wise Sales",
    "backbone_mfr_sales_detail": "Party-wise Sales",
    "klm_group_vs_customer": "Party-wise Sales",
    "customer_item_wise_sale": "Party-wise Sales",
    "kapoor_party_itemwise_sale": "Party-wise Sales",
    "smartpharma_customer_company_sales": "Party-wise Sales",
    "marg_sale_summary_party": "Party-wise Sales",
    "medivision_sale_dc": "Party-wise Sales",
    "product_customer_wise_sales": "Party-wise Sales",
    "klm_company_customer_invoice": "Party-wise Sales",
    "areawise_sales_billwise": "Party-wise Sales",
    "customer_product_sales": "Party-wise Sales",
    "klm_party_wise_statement": "Party-wise Sales",
    "party_item_summary_sr_total": "Party-wise Sales",
    "marg_summary": "Party-wise Sales",
    "marg_register": "Sales Register",
    "marg_register_itemwise": "Party-wise Sales",
    "marg_sale_details": "Party-wise Sales",
    "profitmaker": "Party-wise Sales",
    "sale_register_consolidated": "Party-wise Sales",
    "area_item_summary": "Party-wise Sales",
    "manufacturerwise_billwise": "Party-wise Sales",
    "customerwise_productwise": "Party-wise Sales",
    "billwise_multiheader": "Party-wise Sales",
    "customer_product_grouped": "Party-wise Sales",
    "company_party_summary": "Party-wise Sales",
    "pipe_delimited": "Party-wise Sales",
    "party_item_summary_nofree": "Party-wise Sales",
    "companywise_customerwise": "Party-wise Sales",
    "party_discount_summary": "Party-wise Sales",
    "saraswati_freeissue": "Party-wise Sales",
    "laxmi_mfac": "Party-wise Sales",
    "shree_nath_billwise": "Party-wise Sales",
    "rp_pharma_itemwise": "Party-wise Sales",
    "companywise_areawise": "Party-wise Sales",
    "navkar_productwise": "Party-wise Sales",
    "bajaj_salestatement": "Party-wise Sales",
    "prathna_register": "Party-wise Sales",
    "bharat_saleregister": "Party-wise Sales",
    "tax_invoice": "Party-wise Sales",
    "product_party_wise_list": "Party-wise Sales",
    "product_itemwise_partywise": "Party-wise Sales",
    "customer_itemwise_series": "Party-wise Sales",
    "marg_bordered": "Party-wise Sales",
    "marg_bordered_billwise": "Sales Register",
    "unisolve": "Sales Register",
    "busy_tally": "Party-wise Sales",
    "busy_tally_itemwise": "Party-wise Sales",
    "logic_erp": "Sales Register",
    "wep_legacy": "Party-wise Sales",
    "custom_pharma": "Sales Register",
    "prompt_normal": "Party-wise Sales",
    "prompt_free_qty": "Party-wise Sales",
    "technomax_free_qty": "Party-wise Sales",
    "unknown": "Party-wise Sales",
}

FORMAT_LABELS = {
    "partywise_sales_summary": "Partywise Sales Summary (KAKADE / KLM, party-header running totals over product lines)",
    "customer_invoice_itemwise_sale": "Customer - Invoice - Item Wise Sale (MALU MEDICO / KLM, Marg billwise)",
    "sales_statement_summary_itemwise": "Sales Statement Summary (itemwise, KLM — KRISHNA SAI)",
    "mfacwise_custwise_itemwise": "Mfacwise Custwise Areawise Itemwise (KLM — BALAJI)",
    "prodcust_wise_billwise": "Prod/Cust Wise Sales (SREE SUPREME KLM, positional billwise)",
    "areaprod_wise_billwise": "Area-Prod Wise Sales (SREE SUPREME KLM, positional billwise)",
    "customer_product_wise_packing": "Customer-Product wise Sales (Agrawal KLM, packing + fractional qty/free)",
    "party_item_summary_qtyfree": "Party / Item Wise Sales Summary (QTY + FREE only, no value — AMRITA/KLM)",
    "areawise_sales_statement_banded": "Areawise Sales Statement (CENTRAL AGENCIES / KLM COSMO, AREA+CUSTOMER banded, no rep/code column)",
    "areawise_sales_statement_packing": "Areawise Sales Statment (CENTRAL DISTRIBUTORS, Packing column + named rep code, text/plumber)",
    "prompt_billwise_mixed": "SHRI ASHOK — Prompt ERP Normal party-billwise (mixed-case BillRef: Cash/Credit-L/Credit-O)",
    "shivasakthi_areawise_billwise": "Shree Shivasakthi — Areawise Sales Report (billwise, positional)",
    "vasan_areawise_billwise": "Areawise Sales Report (VASAN KLM billwise, positional)",
    "backbone_mfr_sales_detail": "PURANI HOSPITAL SUPPLIES — BackBone MFR Sales Detail Report (lattice + straddle recovery)",
    "klm_group_vs_customer": "KLM — Group Vs Customer Details (SRI SHIRIDI SAI)",
    "customer_item_wise_sale": "RAKESH Medical — Customer+Item Wise Sale (LOGIC ERP, positional)",
    "kapoor_party_itemwise_sale": "KAPOOR MEDICAL STORE — Party+Item Wise Sale billwise (positional)",
    "smartpharma_customer_company_sales": "SmartPharma360 — Customer-Company wise Product Sales",
    "marg_sale_summary_party": "Universal Medical — Marg SALE SUMMARY party roll-up (text)",
    "bluefox_customerwise_sales": "Customerwise Sales Statement (BlueFox)",
    "customer_product_wise_summary": "Customer-Wise Product-Wise Sales Summary (coded bands)",
    "sale_register_detailed": "Marg — Sale Register Detailed (billwise)",
    "areawise_sales_period": "Area Wise Sales Report (coded party bands, invoice rows)",
    "klm_company_customer_invoice": "KLM — Company, Customer and Invoice Sales",
    "areawise_sales_billwise": "Areawise Sales Report (KLM billwise, positional)",
    "customer_product_sales": "Customer & Product Sales (C.D. Associates)",
    "klm_party_wise_statement": "Party Wise Sales Statement (KLM, DEEPAA, positional)",
    "party_item_summary_sr_total": "Party/Item Wise Sales Summary (SALE/SR/TOTAL, AVR.RATE)",
    "medivision_sale_dc": "MediVision Platinum — Customer/Product-wise Sale-DC (positional, PyMuPDF)",
    "product_customer_wise_sales": "Product-Customer Wise Sales (SwilERP, positional)",
    "marg_summary": "Marg — Sales Detail Summary",
    "marg_register": "Marg — Sales Register",
    "marg_register_itemwise": "Marg — Itemwise Register",
    "marg_sale_details": "Marg — Sale Details",
    "profitmaker": "PROFITMAKER — Customer & Product (Daxinsoft)",
    "sale_register_consolidated": "Sale Register Consolidated",
    "area_item_summary": "Area / Item Wise Sales Summary",
    "manufacturerwise_billwise": "Manufacturerwise Sales (Billwise)",
    "customerwise_productwise": "Customerwise-Productwise (2-line)",
    "billwise_multiheader": "KLM Billwise / Itemwise",
    "customer_product_grouped": "Customer-Product Itemwise (grouped)",
    "company_party_summary": "Company Party-wise Sales Summary",
    "pipe_delimited": "Pipe-delimited Register / Invoice",
    "party_item_summary_nofree": "Party / Item Wise Sales Summary",
    "companywise_customerwise": "Companywise Customerwise Report",
    "party_discount_summary": "Party Discount Summary on Sales",
    "saraswati_freeissue": "Product-Wise Customer-Wise Free Issue",
    "laxmi_mfac": "MFAC Group Wise Report",
    "shree_nath_billwise": "Billwise (Shree Nath style)",
    "rp_pharma_itemwise": "Itemwise Sales Details",
    "companywise_areawise": "Companywise Areawise Sales Detail",
    "navkar_productwise": "Product Wise Sale List (qty-only)",
    "bajaj_salestatement": "Sales Statement (Billwise)",
    "prathna_register": "Sales Detail Register (Mf-Customerwise)",
    "bharat_saleregister": "Sale Register Detailed (Billwise)",
    "tax_invoice": "Tax Invoice (single buyer)",
    "product_party_wise_list": "Marg — Product + Party Wise List",
    "product_itemwise_partywise": "Marg — Item/Party Wise Summary (positional)",
    "customer_itemwise_series": "Customer/Company/Itemwise (Series-banded)",
    "marg_bordered": "Marg — Bordered",
    "marg_bordered_billwise": "Marg — Bordered Billwise",
    "unisolve": "Unisolve",
    "busy_tally": "Busy/Tally",
    "busy_tally_itemwise": "Busy/Tally / Marg Itemwise",
    "logic_erp": "Logic ERP",
    "wep_legacy": "WEP/Legacy",
    "custom_pharma": "Custom Pharma",
    "prompt_normal": "Prompt ERP Normal",
    "prompt_free_qty": "Prompt ERP Free Qty",
    "technomax_free_qty": "Technomax Free Qty",
    "unknown": "Unknown",
}
