#!/usr/bin/env python3
"""
Generate an idempotent Supabase migration that seeds public.product_aliases from
the synonym spellings in product_master.json.

WHY: the live product matcher (Frontends/supabase/functions/_shared/
post-extraction-matcher.ts) resolves an extracted row in three steps —
exact (products_master.normalized_name) -> alias (product_aliases.normalized_alias)
-> fuzzy. The 2700+ synonyms harvested from real reports only help the live
pipeline if they exist as rows in product_aliases. That table is empty, so today
every vendor spelling falls through to fuzzy matching. This migration loads them.

The generated SQL:
  * one statement, a VALUES CTE -> INSERT ... SELECT, joined to products_master by
    (division code, product code) so the 'Klm C 1000' / 'Klm C 1000.' pair (same
    normalized_name) each get the right product_id;
  * normalized_alias computed with the SAME formula as normalizeName() in the edge
    function (lower-case, non-alphanumeric -> space, collapse, trim);
  * ON CONFLICT (normalized_alias) DO NOTHING -> idempotent, safe to re-run/push;
  * source = 'seed' so these are distinguishable from runtime 'auto' aliases.

Skipped (and logged to a sidecar .skipped.txt report), because they would be
unsafe or dead weight under product_aliases' GLOBAL-unique normalized_alias:
  * AMBIGUOUS  — a normalized alias claimed by >1 product (e.g. pack variants
                 'canrolfin cream' -> 15 GM and 30 GM). Cannot pick one safely.
  * REDUNDANT  — normalizes to an existing products_master.normalized_name, so the
                 exact-match step already wins; the alias would never fire.

This is a DATA migration (no schema change), so no schema reload is needed. It is
applied to LOCAL only by us; the user pushes it to live themselves.

Usage:
  python scripts/gen_product_aliases_migration.py            # write the migration + report
  python scripts/gen_product_aliases_migration.py --version 20260625120000
"""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]              # .../Projects/Backends
PROJECTS = ROOT.parent                                  # .../Projects
MASTER_JSON = ROOT / "data" / "product_master.json"
MIGRATIONS_DIR = PROJECTS / "Frontends" / "supabase" / "migrations"

DEFAULT_VERSION = "20260625230000"                      # newest: after every existing migration/history entry
MIGRATION_SLUG = "seed_product_aliases_from_master"


def _normalize_name(name: str) -> str:
    """Mirror of edge normalizeName() / core._normalize_name."""
    if not name:
        return ""
    text = re.sub(r"[^a-zA-Z0-9]+", " ", str(name).lower())
    return re.sub(r"\s+", " ", text).strip()


def _sql(s: str) -> str:
    """Single-quote-escape for a SQL string literal (standard_conforming_strings)."""
    return str(s).replace("'", "''")


def build_rows(catalog: list) -> tuple[list, dict]:
    """Return (rows_to_insert, skip_report).

    rows_to_insert: list of (division, code, alias, normalized_alias), de-duped to
    one row per normalized_alias.
    """
    product_norm_names = {_normalize_name(p["canonical_name"]) for p in catalog}

    # normalized_alias -> set of (division, code) distinct products that claim it
    claims: dict[str, set] = defaultdict(set)
    # normalized_alias -> (division, code, alias_text)  first occurrence, for emit
    first: dict[str, tuple] = {}
    for p in catalog:
        div, code = p.get("division", ""), p.get("code", "")
        for alias in p.get("synonyms", []) or []:
            norm = _normalize_name(alias)
            if not norm:
                continue
            claims[norm].add((div, code))
            first.setdefault(norm, (div, code, alias))

    rows, ambiguous, redundant = [], [], []
    for norm in sorted(first):
        div, code, alias = first[norm]
        if len(claims[norm]) > 1:
            ambiguous.append((norm, sorted(claims[norm])))
            continue
        if norm in product_norm_names:
            redundant.append((norm, alias))
            continue
        rows.append((div, code, alias, norm))

    report = {
        "total_synonyms": sum(len(p.get("synonyms", []) or []) for p in catalog),
        "distinct_norm": len(first),
        "kept": len(rows),
        "ambiguous": ambiguous,
        "redundant": redundant,
    }
    return rows, report


def render_sql(rows: list, version: str) -> str:
    head = f"""-- Seed public.product_aliases from product_master.json synonyms.
-- Generated by Backends/scripts/gen_product_aliases_migration.py — do not hand-edit;
-- re-run the generator after build_product_synonyms.py / sync_product_master.py.
--
-- The live matcher (post-extraction-matcher.ts) resolves products via
-- exact(normalized_name) -> alias(normalized_alias) -> fuzzy. These rows make the
-- alias step hit for the {len(rows)} report spellings harvested so far.
-- Idempotent: ON CONFLICT (normalized_alias) DO NOTHING. source='seed'.

insert into public.product_aliases (product_id, alias, normalized_alias, source)
select pm.id, s.alias, s.norm, 'seed'
from (values
"""
    values = ",\n".join(
        f"  ('{_sql(div)}', '{_sql(code)}', '{_sql(alias)}', '{_sql(norm)}')"
        for (div, code, alias, norm) in rows
    )
    tail = """
) as s(div, code, alias, norm)
join public.divisions d on d.code = s.div
join public.products_master pm on pm.division_id = d.id and pm.code = s.code
on conflict (normalized_alias) do nothing;
"""
    return head + values + tail


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate the product_aliases seed migration from product_master.json")
    ap.add_argument("--version", default=DEFAULT_VERSION, help="Migration version (YYYYMMDDHHMMSS)")
    ap.add_argument("--out-dir", default=str(MIGRATIONS_DIR), help="Migrations directory")
    args = ap.parse_args()

    with MASTER_JSON.open(encoding="utf-8") as fh:
        catalog = json.load(fh)

    rows, report = build_rows(catalog)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    mig_path = out_dir / f"{args.version}_{MIGRATION_SLUG}.sql"
    mig_path.write_text(render_sql(rows, args.version), encoding="utf-8", newline="\n")

    # The skip report is NOT a migration — keep it out of supabase/migrations so the
    # CLI doesn't warn about a non-<timestamp>.sql file. Lives next to this script.
    skip_dir = ROOT / "scripts"
    skip_dir.mkdir(parents=True, exist_ok=True)
    skip_path = skip_dir / f"{args.version}_{MIGRATION_SLUG}.skipped.txt"
    with skip_path.open("w", encoding="utf-8") as fh:
        fh.write(f"# Synonyms NOT seeded into product_aliases (with reasons)\n")
        fh.write(f"# {len(report['ambiguous'])} ambiguous (claimed by >1 product), "
                 f"{len(report['redundant'])} redundant (== a product normalized_name)\n\n")
        fh.write("## AMBIGUOUS\n")
        for norm, owners in report["ambiguous"]:
            fh.write(f"{norm}\t{owners}\n")
        fh.write("\n## REDUNDANT\n")
        for norm, alias in report["redundant"]:
            fh.write(f"{norm}\t({alias})\n")

    print(f"Catalog synonyms: {report['total_synonyms']}  (distinct normalized: {report['distinct_norm']})")
    print(f"Seeding:   {report['kept']} aliases")
    print(f"Skipped:   {len(report['ambiguous'])} ambiguous, {len(report['redundant'])} redundant")
    print(f"Wrote migration: {mig_path}")
    print(f"Wrote skip report: {skip_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
